import "server-only"
import fs from "node:fs"
import path from "node:path"

/**
 * ─────────────────────────────────────────────────────────────────
 * Recipe content loader
 *
 * Each recipe is a folder under `content/recipes/<slug>/`:
 *
 *   content/recipes/
 *     realtime-voice-agent/
 *       recipe.json   ← metadata (hand-edited / CI-stable)
 *
 * The folder name is the slug. The slug is the URL: /recipes/<slug>.
 *
 * To add a new recipe: drop in a new folder with recipe.json.
 * No code changes required — filter taxonomies (platforms, use cases,
 * capabilities) are derived dynamically from the loaded recipes.
 * ─────────────────────────────────────────────────────────────────
 */

const CONTENT_DIR = path.join(process.cwd(), "content", "recipes")
const GENERATED_DIR = path.join(process.cwd(), "content", "generated", "recipes")

/** Canonical ordering for platforms when surfaced to the UI. */
const PLATFORM_ORDER = ["Web", "iOS", "Android"] as const

export type Difficulty = "Beginner" | "Intermediate" | "Advanced"

export type DocLevel = "AGENTS" | "L0" | "L1" | "L2"

export type DocLink = {
  id: string
  label: string
  level: DocLevel
  rawUrl: string
  viewUrl: string
}

export type ProgressiveDisclosure = {
  baseRawUrl: string
  baseViewUrl: string
  docs: DocLink[]
  l2IndexRawUrl: string
  l2IndexViewUrl: string
}

export type FeaturePrompt = {
  id: string
  title: string
  docId: string
  docUrl: string
  purpose: string
  relatedCodeUrls: string[]
  prompt: string
}

type GeneratedRecipeArtifact = {
  schemaVersion: number
  slug: string
  generatedAt: string
  source: {
    githubUrl: string
    agentMdRawUrl: string
    docsBaseRawUrl?: string
  }
  progressiveDisclosure: {
    available: boolean
    docs: DocLink[]
    missing: string[]
  }
  primaryPrompt: string
  featurePrompts: FeaturePrompt[]
}

/** Shape of recipe.json — kept loose so CI/CD can extend it freely. */
export type RecipeMeta = {
  title: string
  tagline: string
  description: string
  platforms: string[]
  useCases: string[]
  capabilities: string[]
  demoUrl: string
  githubUrl: string
  agentMdRawUrl: string
  docsBaseRawUrl?: string
  author: string
  /** ISO 8601 date string, YYYY-MM-DD. */
  updated: string
  difficulty: Difficulty
}

/** A fully-hydrated recipe ready to render. */
export type Recipe = RecipeMeta & {
  /** Folder name. Used as URL segment and stable identifier. */
  slug: string
  /** Derived links for ai-devkit progressive disclosure docs, when available. */
  progressiveDisclosure: ProgressiveDisclosure | null
  /** Generated by scripts/build-recipes.mjs during CI/build. */
  generatedAt?: string
  /** Copyable primary prompt rendered on the recipe page. */
  primaryPrompt: string
  /** Individual prompts generated from top-level progressive disclosure docs. */
  featurePrompts: FeaturePrompt[]
}

export type FilterOptions = {
  platforms: string[]
  useCases: string[]
  capabilities: string[]
}

/* ───────────────────── Schema validation ───────────────────── */

const REQUIRED_STRING_FIELDS: (keyof RecipeMeta)[] = [
  "title",
  "tagline",
  "description",
  "demoUrl",
  "githubUrl",
  "agentMdRawUrl",
  "author",
  "updated",
  "difficulty",
]

const REQUIRED_ARRAY_FIELDS: (keyof RecipeMeta)[] = [
  "platforms",
  "useCases",
  "capabilities",
]

const VALID_DIFFICULTIES: Difficulty[] = [
  "Beginner",
  "Intermediate",
  "Advanced",
]

const STANDARD_DOCS: Omit<DocLink, "rawUrl" | "viewUrl">[] = [
  { id: "agents", label: "AGENTS.md", level: "AGENTS" },
  { id: "l0-repo-card", label: "L0 Repo Card", level: "L0" },
  { id: "l1-01-setup", label: "01 Setup", level: "L1" },
  { id: "l1-02-architecture", label: "02 Architecture", level: "L1" },
  { id: "l1-03-code-map", label: "03 Code Map", level: "L1" },
  { id: "l1-04-conventions", label: "04 Conventions", level: "L1" },
  { id: "l1-05-workflows", label: "05 Workflows", level: "L1" },
  { id: "l1-06-interfaces", label: "06 Interfaces", level: "L1" },
  { id: "l1-07-gotchas", label: "07 Gotchas", level: "L1" },
  { id: "l1-08-security", label: "08 Security", level: "L1" },
  { id: "l2-index", label: "L2 Deep Dives Index", level: "L2" },
]

const STANDARD_DOC_PATHS: Record<(typeof STANDARD_DOCS)[number]["id"], string> = {
  agents: "AGENTS.md",
  "l0-repo-card": "docs/ai/L0_repo_card.md",
  "l1-01-setup": "docs/ai/L1/01_setup.md",
  "l1-02-architecture": "docs/ai/L1/02_architecture.md",
  "l1-03-code-map": "docs/ai/L1/03_code_map.md",
  "l1-04-conventions": "docs/ai/L1/04_conventions.md",
  "l1-05-workflows": "docs/ai/L1/05_workflows.md",
  "l1-06-interfaces": "docs/ai/L1/06_interfaces.md",
  "l1-07-gotchas": "docs/ai/L1/07_gotchas.md",
  "l1-08-security": "docs/ai/L1/08_security.md",
  "l2-index": "docs/ai/L1/L2/_index.md",
}

function assertValidMeta(slug: string, meta: unknown): asserts meta is RecipeMeta {
  if (!meta || typeof meta !== "object") {
    throw new Error(`[recipes] ${slug}/recipe.json is not a JSON object`)
  }
  const m = meta as Record<string, unknown>

  for (const field of REQUIRED_STRING_FIELDS) {
    if (typeof m[field] !== "string" || (m[field] as string).length === 0) {
      throw new Error(
        `[recipes] ${slug}/recipe.json is missing required string field "${field}"`,
      )
    }
  }
  for (const field of REQUIRED_ARRAY_FIELDS) {
    if (!Array.isArray(m[field])) {
      throw new Error(
        `[recipes] ${slug}/recipe.json field "${field}" must be an array`,
      )
    }
  }
  if (!VALID_DIFFICULTIES.includes(m.difficulty as Difficulty)) {
    throw new Error(
      `[recipes] ${slug}/recipe.json difficulty must be one of ${VALID_DIFFICULTIES.join(
        ", ",
      )}`,
    )
  }
  if (
    m.docsBaseRawUrl !== undefined &&
    (typeof m.docsBaseRawUrl !== "string" || m.docsBaseRawUrl.length === 0)
  ) {
    throw new Error(
      `[recipes] ${slug}/recipe.json optional field "docsBaseRawUrl" must be a non-empty string`,
    )
  }
}

function ensureTrailingSlash(url: string): string {
  return url.endsWith("/") ? url : `${url}/`
}

function joinUrl(baseUrl: string, relativePath = ""): string {
  return `${ensureTrailingSlash(baseUrl)}${relativePath}`
}

function rawGithubUrlToViewUrl(rawUrl: string): string {
  const match = rawUrl.match(
    /^https:\/\/raw\.githubusercontent\.com\/([^/]+)\/([^/]+)\/([^/]+)\/?(.*)$/,
  )
  if (!match) return rawUrl

  const [, org, repo, branch, filePath] = match
  const route = rawUrl.endsWith("/") || filePath.length === 0 ? "tree" : "blob"
  return `https://github.com/${org}/${repo}/${route}/${branch}/${filePath}`
}

function buildProgressiveDisclosure(
  docsBaseRawUrl?: string,
): ProgressiveDisclosure | null {
  if (!docsBaseRawUrl) return null

  const baseRawUrl = ensureTrailingSlash(docsBaseRawUrl)
  const baseViewUrl = rawGithubUrlToViewUrl(baseRawUrl)
  const docs = STANDARD_DOCS.map((doc) => {
    const filePath = STANDARD_DOC_PATHS[doc.id]
    const rawUrl = joinUrl(baseRawUrl, filePath)
    return {
      ...doc,
      rawUrl,
      viewUrl: rawGithubUrlToViewUrl(rawUrl),
    }
  })

  const l2Index = docs.find((doc) => doc.id === "l2-index")
  if (!l2Index) {
    throw new Error("[recipes] progressive disclosure L2 index is not configured")
  }

  return {
    baseRawUrl,
    baseViewUrl,
    docs,
    l2IndexRawUrl: l2Index.rawUrl,
    l2IndexViewUrl: l2Index.viewUrl,
  }
}

function buildGeneratedProgressiveDisclosure(
  artifact: GeneratedRecipeArtifact,
): ProgressiveDisclosure | null {
  if (!artifact.progressiveDisclosure.available) return null

  const baseRawUrl = ensureTrailingSlash(
    artifact.source.docsBaseRawUrl ?? artifact.source.agentMdRawUrl.replace(/AGENTS\.md(?:\?.*)?$/, ""),
  )
  const docs = artifact.progressiveDisclosure.docs
  const l2Index = docs.find((doc) => doc.id === "l2-index")

  return {
    baseRawUrl,
    baseViewUrl: rawGithubUrlToViewUrl(baseRawUrl),
    docs,
    l2IndexRawUrl: l2Index?.rawUrl ?? joinUrl(baseRawUrl, "docs/ai/L1/L2/_index.md"),
    l2IndexViewUrl:
      l2Index?.viewUrl ??
      rawGithubUrlToViewUrl(joinUrl(baseRawUrl, "docs/ai/L1/L2/_index.md")),
  }
}

function buildPrimaryPrompt(
  meta: RecipeMeta,
  progressiveDisclosure: ProgressiveDisclosure | null,
): string {
  if (!progressiveDisclosure) {
    return `You are implementing the "${meta.title}" recipe in this project.

Read the recipe AGENTS.md first:
${meta.agentMdRawUrl}

This recipe does not publish ai-devkit progressive disclosure docs yet. Use AGENTS.md as the implementation guide, then inspect the related features and source files in the GitHub repo:
${meta.githubUrl}

Scaffold the recipe in the user's app using the repository's existing setup, architecture, conventions, and feature code. Ask before installing new dependencies.`
  }

  const docsById = new Map(
    progressiveDisclosure.docs.map((doc) => [doc.id, doc.rawUrl]),
  )
  const l1Docs = progressiveDisclosure.docs.filter((doc) => doc.level === "L1")

  return `You are implementing the "${meta.title}" recipe in this project.

Read these files in order. Treat them as the complete recipe spec:

1. ${docsById.get("agents")}
   Agent entry point and repo-specific operating rules.
2. ${docsById.get("l0-repo-card")}
   Repo identity, ownership, and L1 index.
3. Load all L1 summaries as the default working context:
${l1Docs.map((doc) => `   - ${doc.rawUrl}`).join("\n")}
4. ${progressiveDisclosure.l2IndexRawUrl}
   Use the L2 index only when the L1 docs indicate deeper detail is required.

Source repo for cross-reference:
${meta.githubUrl}

Build this recipe into the user's app using the setup, architecture, code map, conventions, workflows, interfaces, gotchas, and security guidance from the docs above. Ask before installing new dependencies.`
}

function loadGeneratedArtifact(slug: string): GeneratedRecipeArtifact | null {
  const artifactPath = path.join(GENERATED_DIR, `${slug}.json`)
  if (!fs.existsSync(artifactPath)) return null

  const rawArtifact = fs.readFileSync(artifactPath, "utf8")
  try {
    const artifact = JSON.parse(rawArtifact) as GeneratedRecipeArtifact
    if (artifact.slug !== slug || typeof artifact.primaryPrompt !== "string") {
      throw new Error("artifact slug or primaryPrompt is invalid")
    }
    return artifact
  } catch (err) {
    throw new Error(
      `[recipes] generated artifact ${slug}.json is invalid: ${(err as Error).message}`,
    )
  }
}

/* ───────────────────── Loader (cached) ───────────────────── */

let _cache: Recipe[] | null = null

function loadRecipesFromDisk(): Recipe[] {
  if (!fs.existsSync(CONTENT_DIR)) {
    // Fail loudly during build; an empty content dir is almost always a bug.
    throw new Error(
      `[recipes] content directory not found at ${CONTENT_DIR}. ` +
        `Did you forget to commit content/recipes/?`,
    )
  }

  const slugs = fs
    .readdirSync(CONTENT_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
    .map((entry) => entry.name)

  const recipes: Recipe[] = slugs.map((slug) => {
    const dir = path.join(CONTENT_DIR, slug)
    const metaPath = path.join(dir, "recipe.json")

    if (!fs.existsSync(metaPath)) {
      throw new Error(`[recipes] ${slug}/recipe.json not found`)
    }

    const rawMeta = fs.readFileSync(metaPath, "utf8")
    let meta: unknown
    try {
      meta = JSON.parse(rawMeta)
    } catch (err) {
      throw new Error(
        `[recipes] ${slug}/recipe.json is not valid JSON: ${(err as Error).message}`,
      )
    }
    assertValidMeta(slug, meta)

    const generated = loadGeneratedArtifact(slug)
    const progressiveDisclosure =
      generated?.progressiveDisclosure.available
        ? buildGeneratedProgressiveDisclosure(generated)
        : buildProgressiveDisclosure(meta.docsBaseRawUrl)

    return {
      slug,
      progressiveDisclosure,
      generatedAt: generated?.generatedAt,
      primaryPrompt: generated?.primaryPrompt ?? buildPrimaryPrompt(meta, progressiveDisclosure),
      featurePrompts: generated?.featurePrompts ?? [],
      ...meta,
    }
  })

  // Newest first — predictable ordering for the home page.
  recipes.sort((a, b) => (a.updated < b.updated ? 1 : -1))
  return recipes
}

export function getAllRecipes(): Recipe[] {
  if (!_cache) _cache = loadRecipesFromDisk()
  return _cache
}

export function getRecipe(slug: string): Recipe | undefined {
  return getAllRecipes().find((r) => r.slug === slug)
}

/* ───────────────────── Derived helpers ───────────────────── */

function uniqueSorted(values: string[], order?: readonly string[]): string[] {
  const set = new Set(values)
  if (order) {
    const ordered = order.filter((v) => set.has(v))
    const extras = [...set].filter((v) => !order.includes(v)).sort()
    return [...ordered, ...extras]
  }
  return [...set].sort((a, b) => a.localeCompare(b))
}

export function getFilterOptions(): FilterOptions {
  const all = getAllRecipes()
  return {
    platforms: uniqueSorted(
      all.flatMap((r) => r.platforms),
      PLATFORM_ORDER,
    ),
    useCases: uniqueSorted(all.flatMap((r) => r.useCases)),
    capabilities: uniqueSorted(all.flatMap((r) => r.capabilities)),
  }
}

/**
 * Related recipes are computed by tag overlap. Use cases weigh slightly
 * more than capabilities since they describe what the recipe is *for*.
 */
export function getRelatedRecipes(slug: string, limit = 3): Recipe[] {
  const current = getRecipe(slug)
  if (!current) return []

  return getAllRecipes()
    .filter((r) => r.slug !== slug)
    .map((r) => {
      const cap = r.capabilities.filter((c) => current.capabilities.includes(c)).length
      const use = r.useCases.filter((u) => current.useCases.includes(u)).length
      return { recipe: r, score: cap * 2 + use * 3 }
    })
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((s) => s.recipe)
}
